# TODO: make some keybindings for other stuff and maybe kill-session

set -g status-right '' # I don't need the date or the time
set -g window-status-current-style ""
set -g status-style 'fg=cyan bg=default fill=default'
set -g message-style 'fg=yellow bg=default fill=default'
set -g renumber-windows 'on'
set -g base-index 1
set -g bell-action none
set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

set -g prefix C-SPACE
unbind C-b
bind C-SPACE send-prefix
bind X kill-session

bind C-r source-file ~/.config/tmux/tmux.conf

