set -g status-style 'fg=#00ffff bg=default fill=default'
set -g message-style 'fg=#ffff00 bg=default fill=default'
set -g renumber-windows 'on'
set -g base-index 1
set -g status-right '' # I don't need the date or the time

# TODO: make some keybindings for other stuff and maybe kill-session
