[font]
# turns out it's the same as the default lol 
normal = { family = "NotoSansM Nerd Font Mono", style = "Regular" }
size = 18

[cursor.style]
blinking = "Never"

[window] # if I ever have a good wallpaper...
opacity = 0.9






















